# Importações

In [1]:
import pandas as pd
from statsforecast import StatsForecast

/home/xande/Desenvolvimento/dengue-arima-fortaleza/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Carregando dataframe

In [2]:
df = pd.read_csv("dataset/fortaleza.csv", index_col="SE")

# Separando dado de teste (ano de 2025)

In [3]:
df["ds"] = pd.to_datetime(df["ds"])
y_test = df[df.ds.dt.year == 2025]

In [4]:
y_test

               ds    y  unique_id
SE
202520 2025-05-11   16          1
202519 2025-05-04   70          1
202518 2025-04-27  109          1
202517 2025-04-20  122          1
202516 2025-04-13  114          1
202515 2025-04-06  102          1
202514 2025-03-30  142          1
202513 2025-03-23  146          1
202512 2025-03-16  154          1
202511 2025-03-09  166          1
202510 2025-03-02  115          1
202509 2025-02-23  105          1
202508 2025-02-16  109          1
202507 2025-02-09  110          1
202506 2025-02-02   84          1
202505 2025-01-26   73          1
202504 2025-01-19   98          1
202503 2025-01-12   68          1
202502 2025-01-05   81          1

# Carregando o modelo treinado anteriormente

In [5]:
model = StatsForecast.load(path="modelos/modelo_2025")

# Predição para o ano de 2025

In [6]:
x_future = pd.DataFrame({
  "ds": y_test.ds.values,
  "unique_id": "1"
})

In [8]:
y_predict = model.predict(h=52, level=[80, 95])
y_predict

,unique_id,ds,AutoARIMA,AutoARIMA-lo-95,AutoARIMA-lo-80,AutoARIMA-hi-80,AutoARIMA-hi-95
0,1,2025-01-05,79.435280,-206.016281,-107.211464,266.082031,364.886841
1,1,2025-01-12,108.732964,-357.061615,-195.833740,413.299652,574.527527
2,1,2025-01-19,140.822357,-477.152069,-263.249390,544.894104,758.796814
3,1,2025-01-26,182.579193,-571.184875,-310.280640,675.439026,936.343323
4,1,2025-02-02,215.116302,-671.539124,-364.636505,794.869080,1101.771729
5,1,2025-02-09,251.371658,-723.536133,-386.086273,888.829590,1226.279419
6,1,2025-02-16,286.262177,-750.200806,-391.444519,963.968872,1322.725098
7,1,2025-02-23,317.391022,-763.146545,-389.134521,1023.916504,1397.928589
8,1,2025-03-02,343.931976,-768.667969,-383.558014,1071.421997,1456.531860
9,1,2025-03-09,358.293030,-777.872070,-384.605408,1101.191406,1494.458130
10,1,2025-03-16,371.565186,-782.041077,-382.737396,1125.867798,1525.171387
11,1,2025-03-23,381.681183,-784.896790,-381.103149,1144.465454,1548.259155
12,1,2025-03-30,415.976501,-760.282654,-353.138031,1185.091064,1592.235718
13,1,2025-04-06,419.633423,-763.869385,-354.217468,1193.484375,1603.136230
14,1,2025-04-13,411.965149,-776.967468,-365.436096,1189.366333,1600.897705
15,1,2025-04-20,410.779938,-782.228333,-369.286255,1190.846069,1603.788208
16,1,2025-04-27,408.641815,-787.428772,-373.426727,1190.710327,1604.712402
17,1,2025-05-04,411.222229,-787.151062,-372.351929,1194.796387,1609.595459
18,1,2025-05-11,413.064087,-787.041626,-371.642853,1197.770996,1613.169800
19,1,2025-05-18,415.582275,-785.827332,-369.977234,1201.141846,1616.991943
20,1,2025-05-25,410.815857,-791.575500,-375.385620,1197.017334,1613.207153
21,1,2025-06-01,416.931152,-786.199524,-369.753723,1203.615967,1620.061768
22,1,2025-06-08,420.821533,-782.866028,-366.227448,1207.870483,1624.509033
23,1,2025-06-15,416.865326,-787.241699,-370.457947,1204.188599,1620.972412
24,1,2025-06-22,419.253906,-785.169189,-368.276031,1206.783813,1623.677002
25,1,2025-06-29,419.626709,-785.034485,-368.058929,1207.312378,1624.287964
26,1,2025-07-06,420.157928,-784.682739,-367.645020,1207.960815,1624.998535
27,1,2025-07-13,420.561157,-784.414673,-367.330200,1208.452515,1625.536987
28,1,2025-07-20,420.894867,-784.182861,-367.063110,1208.852905,1625.972656
29,1,2025-07-27,422.595215,-782.559265,-365.412964,1210.603394,1627.749756
30,1,2025-08-03,424.345245,-780.867126,-363.700775,1212.391235,1629.557617
31,1,2025-08-10,423.218719,-782.037231,-364.855774,1211.293213,1628.474731
32,1,2025-08-17,422.918640,-782.370178,-365.177338,1211.014648,1628.207520
33,1,2025-08-24,424.626892,-780.686646,-363.485291,1212.739136,1629.940430
34,1,2025-08-31,422.091187,-783.241028,-366.033203,1210.215576,1627.423462
35,1,2025-09-07,422.540100,-782.806152,-365.593475,1210.673706,1627.886353
36,1,2025-09-14,423.151337,-782.205566,-364.989166,1211.291870,1628.508179
37,1,2025-09-21,423.221008,-782.143860,-364.924713,1211.366699,1628.585815
38,1,2025-09-28,420.968994,-784.401855,-367.180664,1209.118652,1626.339844
39,1,2025-10-05,422.077423,-783.298035,-366.075226,1210.229980,1627.452881
40,1,2025-10-12,421.383392,-783.995422,-366.771454,1209.538208,1626.762207
41,1,2025-10-19,423.930634,-781.450806,-364.225922,1212.087158,1629.312012
42,1,2025-10-26,424.271912,-781.111450,-363.885925,1212.429688,1629.655273
43,1,2025-11-02,424.718781,-780.666016,-363.439972,1212.877563,1630.103638
44,1,2025-11-09,426.179504,-779.206421,-361.979980,1214.338989,1631.565430
45,1,2025-11-16,427.980194,-777.406555,-360.179840,1216.140259,1633.366943
46,1,2025-11-23,425.738586,-779.648804,-362.421844,1213.899048,1631.125977
47,1,2025-11-30,424.489502,-780.898376,-363.671265,1212.650269,1629.877319
48,1,2025-12-07,424.469238,-780.918945,-363.691742,1212.630249,1629.857422
49,1,2025-12-14,423.347351,-782.041138,-364.813812,1211.508545,1628.735840
50,1,2025-12-21,421.240662,-784.148010,-366.920624,1209.401978,1626.629395
51,1,2025-12-28,421.804932,-783.583923,-366.356445,1209.966309,1627.193726

# Salvando a predição

In [18]:
y_predict.to_csv("predicoes/predicao-py.csv")